title: Michal Golan
theme: minima
description: Algorithm Developer & Researcher

social_links:
  github: https://github.com/migolan
  linkedin: https://www.linkedin.com/in/michal-golan/
  email_html: '<a href="mailto:michal&#46;example&#64;gmail&#46;com">michal@example.com</a>'
  cv: /assets/Michal_Golan_CV.pdf
